control_crop_files:
  - 'data/raw/Crop Yield/clm5_crop_2deg_cpl_cntrl_03_0005-0019_yield_latlon_CLM5mask_6crops.nc'
  - 'data/raw/Crop Yield/clm5_crop_2deg_cpl_cntrl_03m02_0005-0019_yield_latlon_CLM5mask_6crops.nc'
  - 'data/raw/Crop Yield/clm5_crop_2deg_cpl_cntrl_03m03_0005-0019_yield_latlon_CLM5mask_6crops.nc'

control_grass_files:
  - 'data/raw/Grass Production/clm5_crop_2deg_cpl_cntrl_03_0005-0018_yield_latlon_CLM5mask_C3-C4-LEAFC.nc'
  - 'data/raw/Grass Production/clm5_crop_2deg_cpl_cntrl_03m02_0005-0018_yield_latlon_CLM5mask_C3-C4-LEAFC.nc'
  - 'data/raw/Grass Production/clm5_crop_2deg_cpl_cntrl_03m03_0005-0018_yield_latlon_CLM5mask_C3-C4-LEAFC.nc'

scenarios:
  - name: '5Tg'
    crop_files:
      - 'data/raw/Crop Yield/clm5_crop_2deg_cpl_nw_targets_01_0005-0019_yield_latlon_CLM5mask_6crops.nc'
      - 'data/raw/Crop Yield/clm5_crop_2deg_cpl_nw_targets_01m02_0005-0019_yield_latlon_CLM5mask_6crops.nc'
      - 'data/raw/Crop Yield/clm5_crop_2deg_cpl_nw_targets_01m03_0005-0019_yield_latlon_CLM5mask_6crops.nc'
    grass_files:
      - 'data/raw/Grass Production/clm5_crop_2deg_cpl_nw_targets_01_0005-0018_yield_latlon_CLM5mask_C3-C4-LEAFC.nc'
      - 'data/raw/Grass Production/clm5_crop_2deg_cpl_nw_targets_01m02_0005-0018_yield_latlon_CLM5mask_C3-C4-LEAFC.nc'
      - 'data/raw/Grass Production/clm5_crop_2deg_cpl_nw_targets_01m03_0005-0018_yield_latlon_CLM5mask_C3-C4-LEAFC.nc'

  - name: '16Tg'
    crop_files:
      - 'data/raw/Crop Yield/clm5_crop_2deg_cpl_nw_targets_04_0005-0019_yield_latlon_CLM5mask_6crops.nc'
    grass_files:
      - 'data/raw/Grass Production/clm5_crop_2deg_cpl_nw_targets_04_0005-0018_yield_latlon_CLM5mask_C3-C4-LEAFC.nc'

  - name: '27Tg'
    crop_files:
      - 'data/raw/Crop Yield/clm5_crop_2deg_cpl_nw_targets_02_0005-0019_yield_latlon_CLM5mask_6crops.nc'
    grass_files:
      - 'data/raw/Grass Production/clm5_crop_2deg_cpl_nw_targets_02_0005-0018_yield_latlon_CLM5mask_C3-C4-LEAFC.nc'

  - name: '37Tg'
    crop_files:
      - 'data/raw/Crop Yield/clm5_crop_2deg_cpl_nw_targets_03_0005-0019_yield_latlon_CLM5mask_6crops.nc'
    grass_files:
      - 'data/raw/Grass Production/clm5_crop_2deg_cpl_nw_targets_03_0005-0018_yield_latlon_CLM5mask_C3-C4-LEAFC.nc'

  - name: '47Tg'
    crop_files:
      - 'data/raw/Crop Yield/clm5_crop_2deg_cpl_nw_targets_05_0005-0019_yield_latlon_CLM5mask_6crops.nc'
    grass_files:
      - 'data/raw/Grass Production/clm5_crop_2deg_cpl_nw_targets_05_0005-0018_yield_latlon_CLM5mask_C3-C4-LEAFC.nc'

  - name: '150Tg'
    crop_files:
      - 'data/raw/Crop Yield/clm5_crop_2deg_cpl_nw_ur_150_07_0005-0019_yield_latlon_CLM5mask_6crops.nc'
    grass_files:
      - 'data/raw/Grass Production/clm5_crop_2deg_cpl_nw_ur_150_07_0005-0018_yield_latlon_CLM5mask_C3-C4-LEAFC.nc'

shapefile_path: 'data/external/World_Countries__Generalized_/World_Countries__Generalized_.shp'

EPSG: 4326

years: 10

crop_aggregation:
  Corn: ['CornRain', 'CornIrr']
  Rice: ['RiceRain', 'RiceIrr']
  Soy: ['SoyRain', 'SoyIrr']
  Wheat: ['WheatRain', 'WheatIrr']

country_mapping:
  Brunei Darussalam: 'Brunei'
  "Côte d'Ivoire": "Côte d'Ivoire"
  Cabo Verde: 'Cape Verde'
  Curacao: 'Curaçao'
  Congo DRC: 'Democratic Republic of the Congo'
  Congo: 'Republic of Congo'
  Eswatini: 'Swaziland'
  East Timor: 'Timor-Leste'
  North Macedonia: 'Macedonia'
  Palestinian Territory: 'Palestina'
  Pitcairn: 'Pitcairn Islands'
  Réunion: 'Reunion'
  Russian Federation: 'Russia'
  Saint Eustatius: 'Bonaire, Saint Eustatius and Saba'
  Saba: 'Bonaire, Saint Eustatius and Saba'
  Bonaire: 'Bonaire, Saint Eustatius and Saba'
  Saint Martin: 'Saint-Martin'
  South Georgia and South Sandwich Islands: 'South Georgia and the South Sandwich Islands'
  Svalbard: 'Svalbard and Jan Mayen'
  US Virgin Islands: 'Virgin Islands, U.S.'

reference_file_path: 'data/raw/rutgers_nw_production_raw.csv'

output_file_path: 'data/processed/output_150Tg_crops_and_grasses_1.csv'
